### ISSUE TITLE
"Appearance" tab is cut off in preferences menu

### ISSUE THREAD

**Issue by agoe1179** [elementary/browser#3]
## What Happened
Title pretty much says it all. Not a huge deal but doesn't look good. Not affected by resizing the window

![Screenshot from 2021-03-05 02 33 16](https://user-images.githubusercontent.com/5299127/110059150-90d05380-7d5b-11eb-8df2-433eb8401d5e.png)
## Expected Behavior

Text and icons should always scale to fit the tab

## Steps to Reproduce

1. Open Epiphany flatpak
2. Open Preferences
3. Behold

## Platform Information
elementary os 6, latest release

**Comment by Exalm** [comment]
Oh, that's a libhandy bug, and we've fixed it already. Not that the style doesn't need updates, but that's elementary/stylesheet. So nothing to do in ephy really. :)

**Comment by ryonakano** [comment]
The Epiphany on Odin Daily is a *flatpaked* one which uses Adwaita stylesheet (as we can see in the screenshot above), I guess this issue might be due to the bundled Adwaita stylesheet, not our stylesheet.

**Comment by Exalm** [comment]
Not really, libhandy didn't load its bundled styles because `gtk-theme-name` is io.elementary.something. If it did, it would look like this:

![Screenshot from 2021-03-05 14-38-23](https://user-images.githubusercontent.com/1510457/110097205-9744e680-7dc0-11eb-81bc-2ad2c923a4aa.png)

We did this explicitly so elementary can style things :)

**Comment by agoe1179** [comment]
Good to know, thanks for the reply! I will close this issue
