### ISSUE TITLE
Parent window not dimmed when selecting files

### ISSUE THREAD

**Issue by kdwk** [elementary/browser#55]
### What Happened?

https://user-images.githubusercontent.com/39268094/144009424-d6bac7c1-a95b-4fad-bf2e-9af6022ddd65.mp4

After the new Gala update, pop-ups like the file chooser portal is appear on top of the window and dim the parent window to show the hierarchy of windows and express to the user that they must resolve this before they proceed. However, in Web the parent window is not dimmed when the file chooser portal opens.

### Steps to Reproduce

1. Use the select file option on any website to open the file chooser portal
2. Click on anywhere outside the portal. You will receive no response. The user must either choose a file or cancel the operation to proceed
3. The parent window is not dimmed

### Expected Behavior

The parent window is dimmed

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by mcatanzaro** [comment]
It happens with mutter too, so I guess it's probably a GTK issue?

**Comment by mcatanzaro** [comment]
BTW your videos are broken. I think you're using some H.264 profile not supported by OpenH264. If I can't play them in Epiphany or Firefox or Totem.

**Comment by cassidyjames** [comment]
I'm not able to confirm this with Web 41 on elementary OS 6 with the latest Files and Gala updates.

![Screenshot from 2021-11-30 12-05-19](https://user-images.githubusercontent.com/611168/144111369-b9df54e9-7547-4c24-b519-c60e9e891e7f.png)

I'll give a few other combinations a try, but @kdwk have you restarted your session since updating Files and Gala?

**Comment by danrabbit** [comment]
I'm also not able to confirm this with latest updates on OS 6. I believe this should have been fixed in the recent updates to the file chooser portal. Like @cassidyjames pointed out, it'll require a session restart to take effect.

Closing as "Fixed" until OP can confirm they still experience the issue with updates and a restart
