### ISSUE TITLE
Progress bar in address bar

### ISSUE THREAD

**Issue by Odi-3** [elementary/browser#78]
### Problem

Currently Web on elementray no longer has the progress bar in the address bar indicating the loading progress of the requested page.

### Proposal

Reintroducing the progress bar would make Web more consistent with other WebKit-based browsers and the style of AppCenter (here the progress bar indicates the progress of an application installation or update).

**Comment by mcatanzaro** [comment]
It still exists upstream, so if it's gone in elementary OS, that is an elementary-specific change.

(That said, I'll note that other web browsers ditched their progress bars long ago, so its absence might be intentional? I remember experimenting with removing it upstream several years ago, but it had to stay because the only other indication of load progress is the tab bar, so if you have only one tab there's no way to see whether the load is in progress or not.)

**Comment by Odi-3** [comment]
Thank you for your timely and precise answer. Yes, indeed in the version distributed by Gnome it is present and elementary abandoned it starting from version 40 (if I remember correctly). I hope it stays and never gets removed because, as I said, it has become a hallmark of WebKit-based browsers. I know that certain choices shouldn't be made for personal taste but, as a user of the Web, I express my preference and I hope that the collective inclination is this.
